# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 10 Aug 2024 13:12:04 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$CBfEeu1Qz41OLeXsDZuBYuavEPxUJ.RplUJkUSyUnfoknW59e7kQC:admin:admin@example.com:admin,user
